theme: osuny
_merge: deep
params:
  debug:
    productionUrl: https://site.frenchcraftguild.osuny.site
  breadcrumb:
    position: hero-start
  home:
    head:
      title: site
  logo:
    header: "/assets/images/logo-horizontal.svg"
    footer: "/assets/images/logo.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  organizations:
    prefer_image_over_logo: true
  pages:
    index:
      options:
        summary: false
  posts:
    index:
      layout: list
  image_sizes:
    sections:
      organizations:
        item:
          mobile:   400
          tablet:   500
          desktop:  600